apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: wanderlust
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        -   port: 5173
            targetPort: 5173
            protocol: TCP
            nodePort: 31000
              